### ISSUE TITLE
intersectBy

### ISSUE THREAD

**Issue by unhammer** [wrengr/bytestring-trie#1]
I've made an intersectBy function that I'm using (for faster intersection than filter.merge) at https://github.com/unhammer/bytestring-trie-0.2.4/pull/1/files 

If this seems at all useful for anyone else, it'd be very nice to have in the official package, so I don't have to remember to cabal add-source all the time :) It's for 0.2.4.1 though; I haven't had a chance to look into all the changes in 0.3 (which I guess is not quite done yet).

**Comment by unhammer** [comment]
@wrengr should I make this into a PR? (didn't when I first commented here since I think upstream was in darcs back then).

**Comment by wrengr** [comment]
A PR would be great, though do be sure to rebase beforehand (since there's a lot of noise in the current diff due to my removing trailing whitespaces).  The current working version is 0.2.6 which shouldn't be too different from 0.2.4.1 re internals. Alas, the 0.3 branch is still on the back burner for now

**Comment by wrengr** [comment]
@unhammer, Actually, I think I managed to do a cherry-pick that should still give you the author credit.
