### ISSUE TITLE
Conversion to another Trie internal representation

### ISSUE THREAD

**Issue by pyrocto** [wrengr/bytestring-trie#5]
I'd like to convert Tries to another internal representation.  I can do it by using `toList` and writing code to build the NaiveTrie from the list, but that's basically throwing away all the work that your code does.  It would be a lot simpler and smaller code if I had access to the internals:

```
data NaiveTrie a = NaiveTrie !ByteString !(Maybe a) ![NaiveTrie a] deriving Show

toNaiveTrie :: Trie a -> NaiveTrie a
toNaiveTrie Empty              = NaiveTrie "" Nothing []
toNaiveTrie (Arc b v t)        = NaiveTrie b v (dfs t)
toNaiveTrie (Branch p m t1 t2) = NaiveTrie "" Nothing ((dfs t1) ++ (dfs t2))

dfs :: Trie a -> [NaiveTrie a]
dfs Empty              = []
dfs arc@(Arc _ _ _)    = [toNaiveTrie arc]
dfs (Branch _ _ t1 t2) = (dfs t1) ++ (dfs t2)
```

Morally, the internal Trie structure is currently being exposed via `showTrie`, so exposing the structure  completely won't leak any more information.  On the other hand, allowing users to construct Tries directly would allow Tries that violate the invariants.  

How willing would you be to accept a patch providing a datatype isomorphic to Trie, to which Trie can be converted?  It would expose the structure I need while not allowing the isomorphic structure to be used as input to your module's functions.

**Comment by wrengr** [comment]
I don't want to expose the constructors since, as you say, that allows violating invariants. The `showTrie` function is really just there to aid debugging.

Ideally, I'd like to find a better way to meet your needs than adding an isomorphic datatype in the library itself. One option that's already available is to make use of the `Binary` instance, since that leaks all the implementation bits. (First `put` the `Trie`, and then use a custom `get`-like function to build your own representation from the buffer.) Another option would be for me to add a catamorphism function, which I'm perfectly happy to do.
